# Generated by Django 5.2.6 on 2025-10-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_reservation_shop_reservation_shop_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
