# Generated by Django 5.2.6 on 2025-10-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_reservation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
